# EXO 1

In [ ]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn import preprocessing
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.linalg as la

In [ ]:
X = np.array([[1,1,1,2,2,1],[2,1,1,1,2,2]])
X = np.transpose(X)
df = pd.DataFrame(X)
mod1 = (df[0][:,np.newaxis] == df[0].unique()).astype(int)
mod2 = (df[1][:,np.newaxis] == df[1].unique()).astype(int)
M = np.concatenate((mod1,mod2),axis =1)
n,p = M.shape
print(M)
B = np.transpose(M).dot(M)
print(B)
 

[[1 0 1 0]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 0 1]
 [0 1 1 0]
 [1 0 1 0]]
[[4 0 2 2]
 [0 2 1 1]
 [2 1 3 0]
 [2 1 0 3]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  """


In [ ]:
nj = np.sum(M,axis=0) ;  fj= nj/n*p
ni = np.sum(M,axis=1) ;  fi = 1/ni
print(fj)

[2.66666667 1.33333333 2.         2.        ]


In [ ]:
 T = [[(1/(p*np.sqrt(nj[i]*nj[j])))* B[i,j] for i in range(len(nj)) ] for j in range(len(nj)) ]
 T

[[0.25, 0.0, 0.14433756729740646, 0.14433756729740646],
 [0.0, 0.25, 0.10206207261596577, 0.10206207261596577],
 [0.14433756729740646, 0.10206207261596577, 0.25, 0.0],
 [0.14433756729740646, 0.10206207261596577, 0.0, 0.25]]

# EXO 2